### ISSUE TITLE
Previously working Edge Functions ceased to work in v2.49.9

### ISSUE THREAD

**Issue by IsmaelFreitas98** [supabase/supabase#36144]
## Describe the bug

I have a project with a few edge functions, all of them returning the appropriate CORS headers.
After the latest update all functions ceased to work, throwing the following error:

`worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'`

In the frontend the following error is logged:

`Access to fetch at 'http://127.0.0.1:54321/functions/v1/function-name' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

## To Reproduce

- Update the Supabase CLI to the latest version;
- Run Supabase locally using `supabase start`;
- Make a call to any of your edge functions;

## Expected behavior

No errors should be returned when calling an Edge Function.

## System information

- OS: macOS
- Browser: chrome
- Supabase version: v2.49.9

## Additional context

This error does not happen in supabase v2.49.8, and started occurring in v2.49.9

**Comment by beast-nev** [comment]
I am seeing the same thing, had multiple functions which worked before and now fail because of 
```
InvalidWorkerCreation: worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:139:15)
    at async Object.handler (file:///root/index.ts:157:22)
    at async respond (ext:sb_core_main_js/js/http.js:197:14) {
  name: "InvalidWorkerCreation"
}
```

OS: Linux
Supabase version 2.24.3

**Comment by beast-nev** [comment]
Ok I was able to fix it on my end doing the following:

1. Edit `deno.json` to be:
```
{
	"imports": {
		"@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2.49.4",
		"@supabase/functions-js": "https://esm.sh/@supabase/functions-js@2.4.4"
	},
	"compilerOptions": {
		"lib": ["deno.window", "dom"]
	}
}
```
2. Then for me within my function, I was referencing `import { createClient } from 'jsr:@supabase/supabase-js@2';` so now I changed it to `import { createClient } from '@supabase/supabase-js';` and my function now executes correctly.

Not sure if this is the optimal solution or the effects of this change to be honest.

**Comment by leandrocabranes** [comment]
I just tried @beast-nev solution and didn't work at my end.
OS: macOS@15.5
Supabase CLI: 2.24.3
Deno: 2.3.5

The error I get is the following:
```bash
supabase functions serve
Setting up Edge Functions runtime...
Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>
Using supabase-edge-runtime-1.67.4 (compatible with Deno v1.45.2)
serving the request with supabase/functions/assessment-invitation
worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'
worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'
InvalidWorkerCreation: worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:139:15)
    at async Object.handler (file:///root/index.ts:157:22)
    at async respond (ext:sb_core_main_js/js/http.js:197:14) {
  name: "InvalidWorkerCreation"
}
```

**Comment by IsmaelFreitas98** [comment]
> I just tried [@beast-nev](https://github.com/beast-nev) solution and didn't work at my end. OS: macOS@15.5 Supabase CLI: 2.24.3 Deno: 2.3.5

Ensure that you specify the supabase client version where you are importing it.
For instance, if you are importing directly in the function file ensure that you have the following:
`import { createClient } from 'jsr:@supabase/supabase-js@2.49.8';`

**Comment by leandrocabranes** [comment]
@IsmaelFreitas98, nope, same issue. Let me share my files as they are right now:
- `function-name/index.ts`
```javascript
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";
...
```
- `function-name/deno.json`
```json
{
	"imports": {
		"@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2.49.4",
		"@supabase/functions-js": "https://esm.sh/@supabase/functions-js@2.4.4",
		"@supabase/realtime-js": "https://esm.sh/@supabase/realtime-js@2.11.9"
	},
	"compilerOptions": {
		"lib": ["deno.window", "dom"]
	}
}
```

I tried adding and taking away the `"@supabase/realtime-js": "https://esm.sh/@supabase/realtime-js@2.11.9"` line and the issue is still the same.

The error I get is:
```bash
supabase functions serve
Setting up Edge Functions runtime...
Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>
Using supabase-edge-runtime-1.67.4 (compatible with Deno v1.45.2)
serving the request with supabase/functions/assessment-invitation
worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'
worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'
InvalidWorkerCreation: worker boot error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/RealtimeClient' imported from 'file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/realtime-js/2.11.9/dist/module/index.js'
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:139:15)
    at async Object.handler (file:///root/index.ts:157:22)
    at async respond (ext:sb_core_main_js/js/http.js:197:14) {
  name: "InvalidWorkerCreation"
}
```

**Comment by leandrocabranes** [comment]
After trying a couple stuff, what fixed the issue for me was just updating the import of the supabase client inside the edge function code back to the previous version of supabase client, which worked fine, without adding anything to the `deno.json` file.

Like this:
- `index.ts`:
```javascript
import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "jsr:@supabase/supabase-js@2.49.8"
...
```

Still, I hope that the issue gets fixed soon, so the latest version of supabase (2.49.9 as today) is usable for local execution of edge functions.

Thank you @IsmaelFreitas98 for the insight.

**Comment by Hallidayo** [comment]
Hi all, Are you finding this issue in the most recent version?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
